### ISSUE TITLE
Support for the Web Cryptography API (crypto.subtle)

### ISSUE THREAD

**Issue by mhart** [remy/cloud-worker#1]
Cloudflare Workers implements the [Web Cryptography API](https://www.w3.org/TR/WebCryptoAPI/).

Most of the [SubtleCrypto interface](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) seems to be supported AFAICT.

**Comment by remy** [comment]
Yeah, for some reason I left that out! I'll put it in and hopefully I can test with one of CloudFlare's recipes.
