### ISSUE TITLE
Push support?

### ISSUE THREAD

**Issue by easrng** [remy/cloud-worker#3]
How hard would it be to add push event support so you could use this to polyfill web push on mobilesafari?
All i’d need is a Notification class that triggers a user-defined function and a function that lets you trigger a push event in the worker.

**Comment by remy** [comment]
Honestly no idea. I've not played with push yet, but if you want to take a
look you're more than welcome to.

**Comment by easrng** [comment]
Ok. I forked it and will send a PR when i’m done!
